"""
Database layer — SQLite via aiosqlite (Phase 1).
WHY SQLite: Zero config, file-based, perfect for local dev and small loads.
WHEN to upgrade to PostgreSQL: >10k events/day, multi-process writes, team use.
"""

import aiosqlite
import os
import logging

logger = logging.getLogger(__name__)

DB_PATH = "data/security.db"


async def get_db() -> aiosqlite.Connection:
    """Dependency-injectable DB connection."""
    os.makedirs("data", exist_ok=True)
    async with aiosqlite.connect(DB_PATH) as db:
        db.row_factory = aiosqlite.Row
        yield db


async def init_db():
    """Create all tables on first run."""
    os.makedirs("data", exist_ok=True)
    os.makedirs("logs", exist_ok=True)

    async with aiosqlite.connect(DB_PATH) as db:
        await db.executescript("""
        -- ── Login attempts (every login, success or failure) ────────────────
        CREATE TABLE IF NOT EXISTS login_attempts (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp   REAL    NOT NULL,          -- Unix epoch
            ip_address  TEXT    NOT NULL,
            username    TEXT    NOT NULL,
            success     INTEGER NOT NULL DEFAULT 0, -- 0=fail, 1=success
            attack_type TEXT    DEFAULT 'none',     -- brute_force|sqli|xss|none
            severity    TEXT    DEFAULT 'low',      -- low|medium|high|critical
            risk_score  REAL    DEFAULT 0.0,        -- 0.0–1.0 from ML model
            user_agent  TEXT,
            country     TEXT    DEFAULT 'Unknown',
            blocked     INTEGER DEFAULT 0,
            raw_payload TEXT                        -- full JSON for debugging
        );

        -- ── Nginx / app log events ───────────────────────────────────────────
        CREATE TABLE IF NOT EXISTS log_events (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp    REAL NOT NULL,
            source       TEXT NOT NULL,             -- nginx|app|simulated
            ip_address   TEXT,
            method       TEXT,
            path         TEXT,
            status_code  INTEGER,
            response_size INTEGER,
            duration_ms  REAL,
            user_agent   TEXT,
            attack_type  TEXT DEFAULT 'none',
            severity     TEXT DEFAULT 'low',
            risk_score   REAL DEFAULT 0.0,
            flagged      INTEGER DEFAULT 0
        );

        -- ── Security alerts (generated by ML or rules) ───────────────────────
        CREATE TABLE IF NOT EXISTS alerts (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp   REAL NOT NULL,
            alert_type  TEXT NOT NULL,              -- brute_force|anomaly|ddos|sqli
            severity    TEXT NOT NULL,              -- low|medium|high|critical
            ip_address  TEXT,
            username    TEXT,
            message     TEXT NOT NULL,
            details     TEXT,                       -- JSON details
            acknowledged INTEGER DEFAULT 0,
            resolved    INTEGER DEFAULT 0
        );

        -- ── Blocked IPs ──────────────────────────────────────────────────────
        CREATE TABLE IF NOT EXISTS blocked_ips (
            ip          TEXT PRIMARY KEY,
            reason      TEXT,
            blocked_at  REAL NOT NULL,
            expires_at  REAL                        -- NULL = permanent
        );

        -- ── Indexes for fast queries ──────────────────────────────────────────
        CREATE INDEX IF NOT EXISTS idx_login_ip        ON login_attempts(ip_address);
        CREATE INDEX IF NOT EXISTS idx_login_ts        ON login_attempts(timestamp);
        CREATE INDEX IF NOT EXISTS idx_login_attack    ON login_attempts(attack_type);
        CREATE INDEX IF NOT EXISTS idx_log_ts          ON log_events(timestamp);
        CREATE INDEX IF NOT EXISTS idx_alert_ts        ON alerts(timestamp);
        CREATE INDEX IF NOT EXISTS idx_alert_severity  ON alerts(severity);
        """)
        await db.commit()
        logger.info("✅ Database initialized at %s", DB_PATH)
